Repository Encorely/Encorely_iOS, pull requests merged in 2025-08, with the labels that each got.

#24 ✨[Feat] 메인 홈 화면 구현, 컴포넌트 추가, DTO 수정
  Encorely/Encorely/Common/UIComponents/Venue/HallCircleCard.swift
  Encorely/Encorely/Common/UIComponents/Venue/MainVenueCard.swift
  Encorely/Encorely/Common/UIComponents/Venue/ReviewMainRankingCard.swift
  Encorely/Encorely/Common/UIComponents/Venue/ReviewRankingCard.swift
  Encorely/Encorely/Common/UIComponents/Venue/ShowCard.swift
  Encorely/Encorely/Common/UIComponents/Venue/ShowMainCard.swift
  Encorely/Encorely/Common/UIComponents/Venue/UserMainRankingCard.swift
  Encorely/Encorely/Common/UIComponents/Venue/UserRankingCard.swift
  Encorely/Encorely/Models/DTO/Venue/HallDTO.swift
  Encorely/Encorely/Models/DTO/Venue/ReviewRankingDTO.swift
  Encorely/Encorely/Models/DTO/Venue/ShowDTO.swift
  Encorely/Encorely/Models/DTO/Venue/UserRankingDTO.swift
  Encorely/Encorely/Models/Domain/Venue/HallCircleCardType.swift
  Encorely/Encorely/Modules/Tab/Venue/ViewModels/Dummy/FrequentVenueMock.swift
  Encorely/Encorely/Modules/Tab/Venue/ViewModels/Dummy/OngoingShowMock.swift
  Encorely/Encorely/Modules/Tab/Venue/ViewModels/Dummy/ReviewRankingMock.swift
  Encorely/Encorely/Modules/Tab/Venue/ViewModels/Dummy/UserRankingMock.swift
  Encorely/Encorely/Modules/Tab/Venue/Views/MainHomeView.swift
  Encorely/Encorely/Modules/Tab/Venue/Views/OngoingShowView.swift
  Encorely/Encorely/Modules/Tab/Venue/Views/ReviewRankingView.swift
  Encorely/Encorely/Modules/Tab/Venue/Views/UserRankingView.swift
  Encorely/Encorely/Modules/Tab/Venue/Views/VenueListView.swift
  Encorely/Encorely/Resources/Assets/Assets.xcassets/Banner/Contents.json
  Encorely/Encorely/Resources/Assets/Assets.xcassets/Banner/ENCORELY.imageset/Contents.json
  Encorely/Encorely/Resources/Assets/Assets.xcassets/Banner/ENCORELY.imageset/ENCORELY.pdf
  Encorely/Encorely/Resources/Assets/Assets.xcassets/Banner/MainHomeBanner.imageset/Contents.json
  Encorely/Encorely/Resources/Assets/Assets.xcassets/Banner/MainHomeBanner.imageset/MainHomeBanner.pdf
  Encorely/Encorely/Resources/Assets/Assets.xcassets/IconImage/alarm.imageset/Contents.json
  Encorely/Encorely/Resources/Assets/Assets.xcassets/IconImage/alarm.imageset/alarm.pdf
Labels: enhancement

#35 ✨[Feat] ReviewCard
  Encorely/Encorely/Common/UIComponents/Venue/ReviewCard/Card/ReviewFacilityCard.swift
  Encorely/Encorely/Common/UIComponents/Venue/ReviewCard/Card/ReviewFnbCard.swift
  Encorely/Encorely/Common/UIComponents/Venue/ReviewCard/Card/ReviewSeatCard.swift
  Encorely/Encorely/Common/UIComponents/Venue/ReviewCard/HeartandComment.swift
  Encorely/Encorely/Common/UIComponents/Venue/ReviewCard/ReviewLocation.swift
  Encorely/Encorely/Common/UIComponents/Venue/ReviewCard/ReviewRatingTags.swift
  Encorely/Encorely/Common/UIComponents/Venue/ReviewCard/ReviewText.swift
  Encorely/Encorely/Common/UIComponents/Venue/ReviewCard/WholeReviewBtn.swift
  Encorely/Encorely/Models/DTO/Venue/FacilityReviewDTO.swift
  Encorely/Encorely/Models/DTO/Venue/FnbReviewDTO.swift
  Encorely/Encorely/Models/DTO/Venue/SeatReviewDTO.swift
  Encorely/Encorely/Resources/Assets/Assets.xcassets/IconImage/filledHeart.imageset/Contents.json
  Encorely/Encorely/Resources/Assets/Assets.xcassets/IconImage/filledHeart.imageset/filledHeart.pdf
  Encorely/Encorely/Service/MoyaRouter/ShowRouter.swift
Labels: documentation

#38 ✨ [Feat]: 스플래쉬 화면 수정 및 로그인 API연결
  Encorely/Encorely.xcodeproj/project.pbxproj
  Encorely/Encorely/App/EncorelyApp.swift
  Encorely/Encorely/Modules/AppFlow/Login/AuthLinkHandler.swift
  Encorely/Encorely/Modules/AppFlow/Login/AuthRepository.swift
  Encorely/Encorely/Modules/AppFlow/Login/AuthRoute.swift
  Encorely/Encorely/Modules/AppFlow/Login/AuthRoutingView.swift
  Encorely/Encorely/Modules/AppFlow/Login/LoginView.swift
Labels: enhancement

#46 ✨[Feat] 현재 진행 중인 공연 api 연결
  Encorely/Encorely.xcodeproj/project.pbxproj
  Encorely/Encorely/Common/UIComponents/Venue/ShowCard.swift
  Encorely/Encorely/Common/UIComponents/Venue/ShowMainCard.swift
  Encorely/Encorely/Info.plist
  Encorely/Encorely/Models/DTO/Venue/ShowDetailDTO.swift
  Encorely/Encorely/Modules/Tab/Venue/ViewModels/Dummy/FrequentVenueMock.swift
  Encorely/Encorely/Modules/Tab/Venue/ViewModels/ShowViewModel.swift
  Encorely/Encorely/Modules/Tab/Venue/Views/MainHomeView.swift
  Encorely/Encorely/Modules/Tab/Venue/Views/OngoingShowDetailView.swift
  Encorely/Encorely/Modules/Tab/Venue/Views/OngoingShowDetailWrapperView.swift
  Encorely/Encorely/Modules/Tab/Venue/Views/OngoingShowView.swift
  Encorely/Encorely/Service/MoyaService/ShowService.swift
Labels: documentation, enhancement

#48 🍀[ETC] 더미데이터 넣기, 공연장 api 연결
  Encorely/Encorely.xcodeproj/project.pbxproj
  Encorely/Encorely/Common/UIComponents/Venue/MainVenueCard.swift
  Encorely/Encorely/Modules/Tab/Venue/ViewModels/.gitkeep
  Encorely/Encorely/Modules/Tab/Venue/ViewModels/Dummy/ReviewRankingMock.swift
  Encorely/Encorely/Modules/Tab/Venue/ViewModels/Dummy/UserRankingMock.swift
  Encorely/Encorely/Modules/Tab/Venue/ViewModels/HallViewModel.swift
  Encorely/Encorely/Modules/Tab/Venue/ViewModels/ShowViewModel.swift
  Encorely/Encorely/Modules/Tab/Venue/Views/MainHomeView.swift
  Encorely/Encorely/Modules/Tab/Venue/Views/OngoingShowView.swift
  Encorely/Encorely/Modules/Tab/Venue/Views/ReviewRankingView.swift
  Encorely/Encorely/Modules/Tab/Venue/Views/ShowSearchView.swift
  Encorely/Encorely/Modules/Tab/Venue/Views/UserRankingView.swift
  Encorely/Encorely/Modules/Tab/Venue/Views/VenueListView.swift
  Encorely/Encorely/Service/MoyaService/HallService.swift
Labels: documentation, enhancement
